### ISSUE TITLE
Polis Deposit Bug

### ISSUE THREAD

**Issue by TibTub** [pie-flavor/Pieconomy#3]
Hello,

I've encountered an issue with depositing money into a Polis. I'm posting this here, although not sure if it's a pieconomy error or Polis issue, because my console tells me this: https://hastebin.com/pigapawita.rb
Which in part points to pieconomy. I'm happy to move this is if it's not a pieconomy issue, but I thought I'd start somewhere :)

Cheers

**Comment by pie-flavor** [comment]
Right [here](https://github.com/hsyyid/Polis/blob/master/src/main/java/io/github/hsyyid/polis/cmdexecutors/PolisDepositExecutor.java#L36), Polis is blindly assuming there is a server account by the name of the town. So it is a Polis problem. However, if Hassan were to fix it, it would still throw an error, because on my part I am throwing an error when that request gets made instead of simply returning an empty Optional. So we both need to fix our code for it to work.

Meanwhile, the reason this fails is because Pieconomy's 'server accounts' are explicitly defined in the config; there's no support for on-the-fly accounts at the moment. This makes it not ideal for Polis _yet_ since Polis cities are supposed to have a treasury, and you'd hardly want to add a new account to the config and restart the server every time someone makes a new city.
